import path from "path";

import { ESLintUtils } from "@typescript-eslint/utils";

import { getCode } from "../testing/get-code";

import { traceTestRule } from "./_rule";

const ruleTester = new ESLintUtils.RuleTester({
  parser: "@typescript-eslint/parser",
  parserOptions: {
    project: "./tsconfig.json",
    tsconfigRootDir: path.resolve(__dirname, "..", "..", ".."),
    ecmaFeatures: {
      jsx: true,
    },
  },
});

ruleTester.run("tracing/test", traceTestRule, {
  valid: [
    getCode(__dirname, "reassign"),
    getCode(__dirname, "split"),

    getCode(__dirname, "array/access-invalid"),
    getCode(__dirname, "array/access-variable"),
    getCode(__dirname, "array/complex-1"),
    getCode(__dirname, "array/complex-2"),
    getCode(__dirname, "array/destructering"),
    getCode(__dirname, "array/nested"),
    getCode(__dirname, "array/simple"),
    getCode(__dirname, "array/spread-invalid"),
    getCode(__dirname, "array/spread-simple"),

    getCode(__dirname, "class/getter"),
    getCode(__dirname, "class/method-access-mutable"),
    getCode(__dirname, "class/method-access-simple"),
    getCode(__dirname, "class/method-access-with-constructor"),
    getCode(__dirname, "class/static-method-access-mutable"),
    getCode(__dirname, "class/static-method-access-simple"),
    getCode(__dirname, "class/super-method-access-simple"),
    getCode(__dirname, "class/super-method-access-with-constructor"),

    getCode(__dirname, "expression/arrowfunction-map"),
    getCode(__dirname, "expression/arrowfunction-return-1"),
    getCode(__dirname, "expression/arrowfunction-return-2"),
    getCode(__dirname, "expression/assignment"),
    getCode(__dirname, "expression/assignment-bitwise"),
    getCode(__dirname, "expression/await"),
    getCode(__dirname, "expression/binary"),
    getCode(__dirname, "expression/bitwise"),
    getCode(__dirname, "expression/call"),
    getCode(__dirname, "expression/chain"),
    getCode(__dirname, "expression/conditional"),
    getCode(__dirname, "expression/function"),
    getCode(__dirname, "expression/logical"),
    getCode(__dirname, "expression/member"),
    getCode(__dirname, "expression/new"),
    getCode(__dirname, "expression/sequence"),
    getCode(__dirname, "expression/taggedtemplate"),
    getCode(__dirname, "expression/this"),
    getCode(__dirname, "expression/tsasexpression"),
    getCode(__dirname, "expression/tsnonnull"),
    getCode(__dirname, "expression/unary"),
    getCode(__dirname, "expression/update"),

    getCode(__dirname, "function/arrow-function-call"),
    getCode(__dirname, "function/chained-call"),
    getCode(__dirname, "function/first-class"),
    getCode(__dirname, "function/function-declaration-call-chained"),
    getCode(__dirname, "function/function-declaration-call"),
    getCode(__dirname, "function/function-expression-call"),
    getCode(__dirname, "function/generator"),
    getCode(__dirname, "function/iife"),
    getCode(__dirname, "function/nested-call"),
    getCode(__dirname, "function/parameter-array-destructure"),
    getCode(__dirname, "function/parameter-complex-destructure"),
    getCode(__dirname, "function/parameter-multiple"),
    getCode(__dirname, "function/parameter-nested"),
    getCode(__dirname, "function/parameter-object-destructure"),
    getCode(__dirname, "function/parameter-simple"),
    getCode(__dirname, "function/promise-chain"),
    getCode(__dirname, "function/rest-complex"),
    getCode(__dirname, "function/rest-simple"),
    getCode(__dirname, "function/rest-unindexed"),
    getCode(__dirname, "function/return-multiple"),
    getCode(__dirname, "function/return-simple"),
    getCode(__dirname, "function/return-using-override"),
    getCode(__dirname, "function/scope-1"),
    getCode(__dirname, "function/scope-2"),
    getCode(__dirname, "function/tagged-template-expression"),

    getCode(__dirname, "import/dynamic-import"),
    getCode(__dirname, "import/import-aggregate-all-rename"),
    getCode(__dirname, "import/import-aggregate-all-simple"),
    getCode(__dirname, "import/import-aggregate-default"),
    getCode(__dirname, "import/import-aggregate-some-rename"),
    getCode(__dirname, "import/import-aggregate-some-simple"),
    getCode(__dirname, "import/import-all"),
    getCode(__dirname, "import/import-as-renamed"),
    getCode(__dirname, "import/import-default-anonymous-function"),
    getCode(__dirname, "import/import-default-as-renamed"),
    getCode(__dirname, "import/import-default-expression"),
    getCode(__dirname, "import/import-default-function"),
    getCode(__dirname, "import/import-destructure-with-renaming"),
    getCode(__dirname, "import/import-exported-as-default"),
    getCode(__dirname, "import/import-list"),
    getCode(__dirname, "import/import-module"),
    getCode(__dirname, "import/import-renamed"),
    getCode(__dirname, "import/import-simple"),
    getCode(__dirname, "import/require"),

    getCode(__dirname, "object/nested"),
    getCode(__dirname, "object/rest-advanced-1"),
    getCode(__dirname, "object/rest-advanced-2"),
    getCode(__dirname, "object/rest-inline"),
    getCode(__dirname, "object/rest-overwrite"),
    getCode(__dirname, "object/rest-simple"),
    getCode(__dirname, "object/simple"),
    getCode(__dirname, "object/this"),
    getCode(__dirname, "object/without-path"),
  ],
  invalid: [],
});
