export const fsSinks: Map<string, number[]> = new Map([
  ["cp", [0, 1]],
  ["opendir", [0]],
  ["copyFile", [0, 1]],
  ["createWriteStream", [0]],
  ["createReadStream", [0]],
  ["access", [0]],
  ["exists", [0]],
  ["watch", [0]],
  ["unwatchFile", [0]],
  ["watchFile", [0]],
  ["appendFile", [0]],
  ["writeFile", [0]],
  ["readFile", [0]],
  ["utimes", [0]],
  ["open", [0]],
  ["close", [0]],
  ["readdir", [0]],
  ["mkdtemp", [0]],
  ["mkdir", [0]],
  ["rm", [0]],
  ["rmdir", [0]],
  ["unlink", [0]],
  ["realpath", [0]],
  ["readlink", [0]],
  ["symlink", [0, 1]],
  ["link", [0, 1]],
  ["lstat", [0]],
  ["stat", [0]],
  ["lchmod", [0]],
  ["chmod", [0]],
  ["lutimes", [0]],
  ["lchown", [0]],
  ["chown", [0]],
  ["truncate", [0]],
  ["rename", [0, 1]],
]);
